### ISSUE TITLE
Installing AZ Insurance using a Scratch Org throwing Error at step7

### ISSUE THREAD

**Issue by pbreddy01** [trailheadapps/az-insurance#102]
### Summary

Followed all the steps exactly and step 7 is throwing error: 
 Type       Name                                             Problem
![Error](https://user-images.githubusercontent.com/116390808/197287711-62753f26-3a49-4f8b-9706-905400dbf5b5.PNG)
──────────────────────────────────────────────────────────────────────────────── 
 Error        LWR_Demo_Marketing1               The value for urlPathPrefix in ExperienceBundle isn't valid. Check the value and try again.

### Salesforce Org Type

Scratch Org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kishore76** [comment]
I am getting the following errors while completing this step7..

Step7:
sfdx force:source:deploy -m "ApexPage,CustomSite,ExperienceBundle,NavigationMenu,Network,Profile"

Errors:
![image](https://user-images.githubusercontent.com/5725111/200180859-9a5f5337-af3e-499e-8990-f0effc61789a.png)

**Comment by jlraes** [comment]
> I am getting the following errors while completing this step7..
> 
> Step7: sfdx force:source:deploy -m "ApexPage,CustomSite,ExperienceBundle,NavigationMenu,Network,Profile"
> 
> Errors: ![image](https://user-images.githubusercontent.com/5725111/200180859-9a5f5337-af3e-499e-8990-f0effc61789a.png)

Hi this can be fixed by removing '/s' in the urlPahtPrefix in the Experience site-meta.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ExperienceBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <label>LWR Demo Agent</label>
    <type>ChatterNetworkPicasso</type>
    <urlPathPrefix>agent**/s**</urlPathPrefix>
</ExperienceBundle>

**Comment by smccurry-sovrn** [comment]
Any update on this issue?  Removing the '/s' did not work for me.

**Comment by jimpoteet** [comment]
Getting the same error. Removing the "/" for urlPathPrefix didn't work for me.
<img width="861" alt="image" src="https://user-images.githubusercontent.com/1998657/202517089-90b7507e-4c66-4af8-92e3-9c6da8d61a2f.png">

**Comment by amanrawatdc** [comment]
Facing same issue, build as jimpoteet, has anyone been able to deploy this project  in a scratch org ?

**Comment by jlraes** [comment]
Yes I was able to deploy to a scratch org just last week after numerous attempts. I thought it was fixed by modifying the urlPathPrefix in the Experience site-meta.xml, but apparenlty it was some other change or temporary condition that allowed me to deploy to a scratch org just once.

**Comment by kurleabhijeet** [comment]
Any updates on this? I am also getting the same issue
![image](https://user-images.githubusercontent.com/11027029/203525309-78a6920d-6096-4e4b-8092-d5f0b4f26d17.png)

**Comment by muenzpraeger** [comment]
Long story short: we'll have to "re-build" the app, as there have been some metadata changes in Winter '23 in LWR. This will eventually happen until end of next week.

**Comment by raunay** [comment]
I'm having this issue too on sourceApiVersion 52 and 56:

`The value for urlPathPrefix in ExperienceBundle isn't valid. Check the value and try again.`

**Comment by akkibaddiex** [comment]
I am facing the same issue as well, any update on the time line of the fix...

**Comment by ybiyani** [comment]
I too am seeing this issue

**Comment by ybiyani** [comment]
> Long story short: we'll have to "re-build" the app, as there have been some metadata changes in Winter '23 in LWR. This will eventually happen until end of next week.

@muenzpraeger  - Any updates?

**Comment by tompatros** [comment]
Also affected by this error - any ETA?

**Comment by kevinfleck513** [comment]
stuck @ step 7 as well, anybody ever fix this?

**Comment by muenzpraeger** [comment]
The reason is hard to track down, so we're currently looking into either re-creating the project source, or moving (incl. some changes) to Enhanced LWR/CMS. 

Should be decided/implemented by begin of next week. Sorry for the delay, lots of projects atm to juggle.

**Comment by muenzpraeger** [comment]
Quick heads up: we're still looking at the right way to move/migrate the app. As Enhanced LWR/CMS doesn't have yet an import functionality we're still looking at the right options.

**Comment by ygavrylenko** [comment]
As @muenzpraeger  is working on more long-term solution, here is a quick fix for the problem:

1. before the step 7, disable enhanced domains in the org, wait till the change take an effect
2. you need to change you local sfdx config file for the connection .sfdx/<username> and past the new instanceUrl from the new enhanced domain
3. go on with step 7

**Comment by muenzpraeger** [comment]
Tracking work with work item W-12432175

**Comment by djohnsonb** [comment]
I am getting this error 

 sfdx force:source:deploy -m ""ApexPage,CustomSite:LWR_Demo_Agent,ExperienceBundle:LWR_Demo_Agent1,NavigationMenu:Agent_Main_Navigation,Network:LWR Demo Agent,Profile""
ERROR running force:source:deploy:  Unexpected arguments: Demo, Agent,Profile
See more help with --help

=== Component Failures [1]

 Type  Name                Problem                                                                                     
 ───── ─────────────────── ─────────────────────────────────────────────────────────────────────────────────────────── 
 Error LWR_Demo_Marketing1 The value for urlPathPrefix in ExperienceBundle isn't valid. Check the value and try again.

**Comment by muenzpraeger** [comment]
Patch is live
