### ISSUE TITLE
ConnectApi.ManagedContent.getManagedContentKeys() is working in Enhanced LWR site.

### ISSUE THREAD

**Issue by AkhilRajMR** [trailheadapps/az-insurance#122]
The code which is used to fetch managed content by key is not working in enhanced LWR channel. It's showing access issue. But it's working fine in Aura channel. Could you please help me to solve this issue.

**Comment by muenzpraeger** [comment]
Sorry for the late reply. This app is currently only for regular CMS, not enhanced CMS.
