### ISSUE TITLE
Error  force-app/main/default/experiences/LWR_Demo_Agent1.site-meta.xml  Required ThemeLayouts are missing in the layouts section of LWR_Demo_Agent1/themes/buildYourOwnLWR.json. Add mappings for ServiceNotAvailable and try again.

### ISSUE THREAD

**Issue by kai-wang** [trailheadapps/az-insurance#16]
Hi there,

I got this the below error when deploying the community 

Error  force-app/main/default/experiences/LWR_Demo_Agent1.site-meta.xml  Required ThemeLayouts are missing in the layouts section of LWR_Demo_Agent1/themes/buildYourOwnLWR.json. Add mappings for ServiceNotAvailable and try again. 

Regards,

**Comment by scottbarter** [comment]
Hi there, same issue here.

**Comment by muenzpraeger** [comment]
Fixed in `main`, sorry for the delay, Dreamforce kept us busy
