### ISSUE TITLE
cannot read contentId of undefined

### ISSUE THREAD

**Issue by catenaprotocol** [trailheadapps/az-insurance#25]
### Summary

I can't read contentId and crashing the component inside the community
I can't pass in input at the apex methods the variable of contentId because it's undefined
### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by muenzpraeger** [comment]
Please provide a detailed description as per the issue template. Otherwise it's hard to identify where you experience it.

**Comment by muenzpraeger** [comment]
@catenaprotocol Can you give me more details, or can I close the issue as you resolved it?
