### ISSUE TITLE
Search component in the menu navigation in community /experience site

### ISSUE THREAD

**Issue by ahamed-WK** [trailheadapps/az-insurance#31]
**What is missing from the application? Please describe.**
Search component in the menu navigation in community /experience site

**Describe the solution you'd like**
[Similar to the aura function ](https://trailhead.salesforce.com/en/content/learn/projects/communities_theme_layout/custom_search)

**Describe alternatives you've considered**
NA

**Additional context**
https://trailhead.salesforce.com/en/content/learn/projects/communities_theme_layout/custom_search
Similar to the aura app

**Comment by muenzpraeger** [comment]
@ahamed-WK Unsure if I understand the request. Search is not part of this application, but feel free to submit a PR that integrates such an element.
