### ISSUE TITLE
Error when deploying into a SDO / Enterprise org

### ISSUE THREAD

**Issue by andreadipalma** [trailheadapps/az-insurance#33]
### Summary
Got an error when doing the following installation step:

adipalma-ltm1:config adipalma$ sfdx force:source:deploy -m ApexPage,CustomSite,ExperienceBundle,NavigationMenu,Network,Profile
*** Deploying with SOAP API ***
Deploy ID: 0Af0900000MrR4ECAV
SOURCE PROGRESS | ████████████████████████████████████░░░░ | 10/11 Components

=== Component Failures [1]
Type   Name             Problem
─────  ───────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  LWR_Demo_Agent1  Required ThemeLayouts are missing in the layouts section of LWR_Demo_Agent1/themes/buildYourOwnLWR.json. Add mappings for ServiceNotAvailable and try again.

### Steps To Reproduce:
I used the steps reported in the main readme file. Only difference is that I’m using a standard org not a scratch org.

**Comment by johan101486** [comment]
Has there been any movement or update on this issue? Thanks

**Comment by andreadipalma** [comment]
Hi
please close it, I've handled it with a workaround to fix the issue with
configuration of the template.

I'll post in a comment the modifications I made.
Thanks
Andrea

**Comment by muenzpraeger** [comment]
Fixed in `main`, sorry for the delay, Dreamforce kept us busy

**Comment by andreadipalma** [comment]
Thank you!!!!
