### ISSUE TITLE
Facing Error 'SiteDotCom source file expected' while deploying

### ISSUE THREAD

**Issue by pradeepchary** [trailheadapps/az-insurance#53]
### Summary

Hi, I am facing the below error while deploying. I see there are no have SiteDotCom metadata files in the repository.

ERROR running force:source:deploy:  ../az-insurance/force-app/main/default/sites/LWR_Demo_Agent.site-meta.xml: Expected source files for type 'SiteDotCom'

### Salesforce Org Type

Scratch Org

### Steps To Reproduce

While running the cmd 
sfdx force:source:deploy -m ApexPage,CustomSite,ExperienceBundle,NavigationMenu,Network,Profile

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muenzpraeger** [comment]
@mshanemc I feel that this falls into the realm of the Salesforce CLI, as the error happens immediately after running the `deploy` command. And Experience Cloud LWR sites don't have `SiteDotCom` metadata. Thank for looking into it!

FYI @zhawtof @gtabboud

**Comment by pradeepchary** [comment]
Any updates on this issue? Or any workaround for the time being, please suggest. Thank you.

**Comment by muenzpraeger** [comment]
@pradeepchary Can you please update the Salesforce CLI (using `sfdx update`), and then try again? The most recent version should have fixed that. Thanks!

**Comment by pradeepchary** [comment]
@muenzpraeger the issue is fixed, was able to deploy, thank you
